PostCard 디자인 수정, 타입 추가
codeit-frontend-part3-team3/The-julge pull request #130
Opened 2024-12-29 11:28 UTC by Hogn-hyeonbin

### 이슈 번호

close #'124'

### 작업 사항 요약

디자인 크기 수정 ,타입 추가 , useRouter 적용
카드안에 버튼이 크기에 따라 카드 밖으로 빠져 나오는 오류 수정
PostCard에 공고 상세 타입 추가

2024-12-29 11:48 UTC, Stemplun requested changes
이미지 경로만 수정해주시면 될 것 같습니다!

2024-12-29 11:48 UTC, Stemplun commented on src/app/_components/PostCard/PostCardV2.tsx
> +                src='./image/clock-icon.svg'
여기 경로를 안고치신것 같아요!

2024-12-29 11:48 UTC, Stemplun commented on src/app/_components/PostCard/PostCardV2.tsx
> +                src='./image/path11.svg'
여기도요!

2024-12-29 15:14 UTC, Hogn-hyeonbin commented
넵 수정 완료 했습니다

2024-12-29 18:46 UTC, swp91 approved these changes
고생하셨습니다 👍 저도 postcard 좀 수정한게있어서 머지하실떄 충돌 한번만 봐주세용~

2024-12-30 00:35 UTC, Stemplun approved these changes

2024-12-30 02:57 UTC, merged