헤더 알림 공통 컴포넌트
codeit-frontend-part3-team3/The-julge pull request #51
Opened 2024-12-17 08:46 UTC by Hogn-hyeonbin

### 43

close #'43'

### 작업 사항 요약
알림 모달 기능 구현
아직 미완성이긴 합니다...
api 연동도 해야되고 연동 되었을 떄 디자인도 수정해야 될 것 같습니다
성우님이 만들어 주신 notificaion 커스텀 훅 import해서 사용하게 바꿔야 됩니다.

### 작업 결과

2024-12-17 12:01 UTC, Stemplun approved these changes
알림 모달을 잘 구현해주셨네요!!
api연결은 차근차근 하면 될 것 같습니다!

2024-12-17 12:01 UTC, Stemplun commented on src/app/_components/NotificationModal/NotificationModal.tsx
> +}, [isOpen, userId]);
dependencies에 userId는 필요없을 것 같습니다!

2024-12-17 12:45 UTC, swp91 requested changes

2024-12-17 12:45 UTC, swp91 commented on src/app/_components/NotificationModal/NotificationModal.tsx
> +// NotificationModal.tsx
useEffect나 useState같은 훅 쓰실때는 상단에 'use client' 라고 선언해 주셔야됩니다!
기본이 서버 컴포넌트라서 클라이언트컴포넌트로 전환해주셔야되용
그리고 임시데이터라도 넣으셔서 잘 되는지 테스트 한번 부탁드립니다!👍

2024-12-17 16:36 UTC, Hogn-hyeonbin commented on src/app/_components/NotificationModal/NotificationModal.tsx
> +// NotificationModal.tsx
좋은 정보 감사합니다 저는 테스트 할떄 page.tsx에 상단에만 'useclient' 선언했었는데 여기에 반영 하겠습니다. 일단 더미 데이터를 넣고 테스트 했을땐 오류 없긴 했습니다.

2024-12-17 16:37 UTC, Hogn-hyeonbin commented on src/app/_components/NotificationModal/NotificationModal.tsx
> +}, [isOpen, userId]);
넵 확인햇습니다 감사합니다!

2024-12-18 03:56 UTC, swp91 approved these changes

2024-12-18 04:44 UTC, merged